### ISSUE TITLE
Errors are not captured and presented in the Dashboard

### ISSUE THREAD

**Issue by seamm** [molssi-seamm/seamm_jobserver#3]
* JobServer version: 2021.6.x
* Python version: 3.9
* Operating System: MacOS

### Description

When there is an error in a flowchart, the exception and traceback are printed to the terminal running the JobServer, but not captured and added to the results displayed in the DashBoard. Also the job status is **Finished**, not **Error**.

### What I Did

In tutorial-3 I had a typo in the FromSMILES step:
```
Starting job 11 at /Users/psaxe/SEAMM/Jobs/projects/default/Job_000011
Error running the flowchart

Traceback (most recent call last):
  File "/Users/psaxe/opt/miniconda3/envs/seamm/lib/python3.9/site-packages/seamm/exec_flowchart.py", line 166, in run
    next_node = next_node.run()
  File "/Users/psaxe/opt/miniconda3/envs/seamm/lib/python3.9/site-packages/from_smiles_step/from_smiles.py", line 135, in run
    P = self.parameters.current_values_to_dict(
  File "/Users/psaxe/opt/miniconda3/envs/seamm/lib/python3.9/site-packages/seamm/parameters.py", line 660, in current_values_to_dict
    data[key] = self[key].get(context=context, formatted=formatted, units=units)
  File "/Users/psaxe/opt/miniconda3/envs/seamm/lib/python3.9/site-packages/seamm/parameters.py", line 317, in get
    result = eval(self.value[1:], context)
  File "<string>", line 1
    _row["SMILES']
                 ^
SyntaxError: EOL while scanning string literal

CRITICAL:seamm.exec_flowchart:Error running the flowchart
```
This is the output in the JobServer window, but it does not appear in the DashBoard.

**Comment by janash** [comment]
@seamm - The dashboard does not make any decisions about the state of the job. The job state/status is always read and presented based on what is present in the job directory. The job status is read from by the dashboard from what shows up in "state" in `job_data.json`. This is handled by SEAMM and not by the dashboard. Can you check the job state from `job_data.json`?

The dashboard is completely separate from SEAMM. If it's not picking up the error it's because the error is not being sent to it by SEAMM. If you would like the error message displayed it can be added as a file to the folder. We could also consider making the error message the "job description" so that it displayed by default when the job is loaded in the dashboard.

**Comment by seamm** [comment]
Correct, and that is why this issues is in JobServer, not Dashboard. The Dashboard relies on the correct information comping from the job or JobServer 

-------------
Paul Saxe
Lead Software Scientist
The Molecular Sciences Software Institute (MolSSI)
Virginia Tech
Blacksburg, VA 24061
work: +1.540.231.0761
  cell: +1.505.603.8182
